package xyz.przemyk.simpleplanes.client.render.models;

import java.util.Map;

import static java.util.Map.entry;

/**
 * Where each named cube's UV net starts in the airliner textures, one table per size and layer: the metal layer
 * ({@code *_metal.png}, 256x256, also the fans) and the painted skin ({@code *_skin.png}). Generated together
 * with the textures from the cube list of {@link AirlinerShape}; do not edit by hand.
 */
final class AirlinerUv {

    private AirlinerUv() {}

    // @UV-BEGIN WIDE_METAL
    static final Map<String, int[]> WIDE_METAL = Map.ofEntries(
            entry("belt", new int[]{0, 0}),
            entry("cockpit_side", new int[]{149, 43}),
            entry("ws_upper", new int[]{88, 9}),
            entry("ws_lower", new int[]{88, 15}),
            entry("dash", new int[]{88, 0}),
            entry("door", new int[]{67, 4}),
            entry("cowl", new int[]{0, 0}),
            entry("pylon", new int[]{202, 0}),
            entry("logo_0", new int[]{170, 0}),
            entry("logo_1", new int[]{88, 22}),
            entry("logo_2", new int[]{173, 59}),
            entry("logo_3", new int[]{0, 95}),
            entry("logo_4", new int[]{61, 95}),
            entry("logo_5", new int[]{122, 95}),
            entry("crew_base", new int[]{0, 34}),
            entry("crew_back", new int[]{88, 22}),
            entry("crew_head", new int[]{88, 39}),
            entry("seat_base", new int[]{37, 34}),
            entry("seat_back", new int[]{34, 47}),
            entry("seat_head", new int[]{61, 47}),
            entry("winglet_a", new int[]{227, 0}),
            entry("winglet_b", new int[]{231, 23}),
            entry("lip_h", new int[]{120, 22}),
            entry("lip_v", new int[]{231, 48}),
            entry("exhaust", new int[]{120, 28}),
            entry("plug", new int[]{0, 0}),
            entry("apu", new int[]{231, 37}),
            entry("nose_strut", new int[]{227, 0}),
            entry("main_strut", new int[]{50, 4}),
            entry("nose_tyre", new int[]{244, 0}),
            entry("main_tyre", new int[]{202, 0}),
            entry("spinner", new int[]{59, 4}),
            entry("blade", new int[]{50, 0}));
    // @UV-END WIDE_METAL

    // @UV-BEGIN WIDE_SKIN
    static final Map<String, int[]> WIDE_SKIN = Map.ofEntries(
            entry("body_lower", new int[]{0, 0}),
            entry("body_upper", new int[]{622, 137}),
            entry("hull_low", new int[]{241, 141}),
            entry("hull_high", new int[]{0, 153}),
            entry("fuselage_shoulder_top", new int[]{365, 0}),
            entry("fuselage_crown_low", new int[]{608, 0}),
            entry("fuselage_crown", new int[]{464, 394}),
            entry("fuselage_shoulder_bottom", new int[]{0, 281}),
            entry("fuselage_keel", new int[]{655, 394}),
            entry("fuselage_fairing", new int[]{241, 0}),
            entry("nose_1", new int[]{831, 53}),
            entry("nose_2", new int[]{0, 0}),
            entry("nose_3", new int[]{0, 47}),
            entry("nose_4", new int[]{304, 56}),
            entry("nose_5", new int[]{0, 88}),
            entry("nose_6", new int[]{241, 96}),
            entry("nose_7", new int[]{405, 56}),
            entry("tail_1", new int[]{608, 0}),
            entry("tail_2", new int[]{394, 0}),
            entry("tail_3", new int[]{608, 56}),
            entry("tail_4", new int[]{831, 0}),
            entry("fin_fillet", new int[]{455, 49}),
            entry("fin_1", new int[]{414, 49}),
            entry("fin_2", new int[]{956, 46}),
            entry("fin_3", new int[]{241, 0}),
            entry("fin_4", new int[]{909, 0}),
            entry("fin_5", new int[]{988, 46}),
            entry("fin_6", new int[]{909, 25}),
            entry("wing_1", new int[]{831, 0}),
            entry("wing_2", new int[]{909, 0}),
            entry("wing_3", new int[]{241, 56}),
            entry("wing_4", new int[]{655, 64}),
            entry("wing_5", new int[]{933, 81}),
            entry("wing_6", new int[]{432, 95}),
            entry("stab_1", new int[]{608, 94}),
            entry("stab_2", new int[]{241, 30}),
            entry("stab_3", new int[]{978, 24}),
            entry("stab_4", new int[]{952, 46}),
            entry("pillar_0", new int[]{284, 0}),
            entry("pillar_1", new int[]{394, 0}),
            entry("pillar_2", new int[]{831, 26}),
            entry("pillar_3", new int[]{241, 0}),
            entry("pillar_4", new int[]{269, 0}),
            entry("pillar_5", new int[]{909, 0}),
            entry("pillar_6", new int[]{932, 0}),
            entry("pillar_7", new int[]{978, 0}),
            entry("pillar_8", new int[]{1001, 0}),
            entry("pillar_9", new int[]{241, 11}),
            entry("pillar_10", new int[]{269, 11}),
            entry("pillar_11", new int[]{978, 0}),
            entry("liner_floor", new int[]{478, 268}),
            entry("liner_ceiling", new int[]{237, 270}),
            entry("liner_wall_low", new int[]{229, 402}),
            entry("liner_wall_high", new int[]{0, 419}),
            entry("liner_front_low", new int[]{339, 95}),
            entry("liner_front_top", new int[]{831, 107}),
            entry("liner_front_side", new int[]{256, 0}));
    static final int[] WIDE_SKIN_SIZE = {1024, 1024};
    // @UV-END WIDE_SKIN

    // @UV-BEGIN REGIONAL_METAL
    static final Map<String, int[]> REGIONAL_METAL = Map.ofEntries(
            entry("belt", new int[]{0, 0}),
            entry("cockpit_side", new int[]{61, 20}),
            entry("ws_upper", new int[]{100, 0}),
            entry("ws_lower", new int[]{171, 0}),
            entry("dash", new int[]{0, 0}),
            entry("door", new int[]{169, 7}),
            entry("cowl", new int[]{193, 7}),
            entry("pylon", new int[]{58, 0}),
            entry("logo_0", new int[]{100, 6}),
            entry("logo_1", new int[]{161, 7}),
            entry("logo_2", new int[]{0, 9}),
            entry("logo_3", new int[]{193, 37}),
            entry("logo_4", new int[]{168, 96}),
            entry("logo_5", new int[]{0, 107}),
            entry("crew_base", new int[]{132, 12}),
            entry("crew_back", new int[]{0, 9}),
            entry("crew_head", new int[]{0, 26}),
            entry("seat_base", new int[]{32, 20}),
            entry("seat_back", new int[]{225, 36}),
            entry("seat_head", new int[]{132, 27}),
            entry("winglet_a", new int[]{100, 6}),
            entry("winglet_b", new int[]{236, 0}),
            entry("lip_h", new int[]{132, 6}),
            entry("lip_v", new int[]{80, 0}),
            entry("exhaust", new int[]{61, 46}),
            entry("plug", new int[]{59, 9}),
            entry("apu", new int[]{100, 24}),
            entry("nose_strut", new int[]{100, 6}),
            entry("main_strut", new int[]{193, 7}),
            entry("nose_tyre", new int[]{80, 20}),
            entry("main_tyre", new int[]{225, 51}),
            entry("spinner", new int[]{32, 13}),
            entry("blade", new int[]{32, 9}));
    // @UV-END REGIONAL_METAL

    // @UV-BEGIN REGIONAL_SKIN
    static final Map<String, int[]> REGIONAL_SKIN = Map.ofEntries(
            entry("body_lower", new int[]{353, 0}),
            entry("body_upper", new int[]{562, 141}),
            entry("hull_low", new int[]{0, 145}),
            entry("hull_high", new int[]{333, 149}),
            entry("fuselage_shoulder_top", new int[]{0, 0}),
            entry("fuselage_crown_low", new int[]{690, 0}),
            entry("fuselage_crown", new int[]{392, 406}),
            entry("fuselage_shoulder_bottom", new int[]{201, 281}),
            entry("fuselage_keel", new int[]{563, 406}),
            entry("fuselage_fairing", new int[]{211, 0}),
            entry("nose_1", new int[]{562, 0}),
            entry("nose_2", new int[]{885, 0}),
            entry("nose_3", new int[]{885, 39}),
            entry("nose_4", new int[]{623, 43}),
            entry("nose_5", new int[]{362, 43}),
            entry("nose_6", new int[]{286, 47}),
            entry("nose_7", new int[]{996, 0}),
            entry("tail_1", new int[]{0, 0}),
            entry("tail_2", new int[]{651, 0}),
            entry("tail_3", new int[]{562, 43}),
            entry("tail_4", new int[]{211, 0}),
            entry("fin_fillet", new int[]{387, 0}),
            entry("fin_1", new int[]{732, 0}),
            entry("fin_2", new int[]{966, 12}),
            entry("fin_3", new int[]{773, 0}),
            entry("fin_4", new int[]{93, 0}),
            entry("fin_5", new int[]{323, 0}),
            entry("fin_6", new int[]{116, 0}),
            entry("wing_1", new int[]{323, 0}),
            entry("wing_2", new int[]{387, 0}),
            entry("wing_3", new int[]{398, 38}),
            entry("wing_4", new int[]{71, 26}),
            entry("wing_5", new int[]{751, 46}),
            entry("stab_1", new int[]{696, 46}),
            entry("stab_2", new int[]{966, 46}),
            entry("stab_3", new int[]{970, 0}),
            entry("stab_4", new int[]{83, 0}),
            entry("pillar_0", new int[]{0, 0}),
            entry("pillar_1", new int[]{116, 0}),
            entry("pillar_2", new int[]{732, 0}),
            entry("pillar_3", new int[]{323, 0}),
            entry("pillar_4", new int[]{342, 0}),
            entry("pillar_5", new int[]{387, 0}),
            entry("pillar_6", new int[]{406, 0}),
            entry("pillar_7", new int[]{446, 0}),
            entry("pillar_8", new int[]{464, 0}),
            entry("pillar_9", new int[]{722, 0}),
            entry("pillar_10", new int[]{749, 0}),
            entry("pillar_11", new int[]{801, 0}),
            entry("pillar_12", new int[]{773, 0}),
            entry("pillar_13", new int[]{446, 0}),
            entry("liner_floor", new int[]{538, 276}),
            entry("liner_ceiling", new int[]{0, 278}),
            entry("liner_wall_low", new int[]{744, 278}),
            entry("liner_wall_high", new int[]{0, 408}),
            entry("liner_front_low", new int[]{211, 47}),
            entry("liner_front_top", new int[]{0, 51}),
            entry("liner_front_side", new int[]{357, 0}));
    static final int[] REGIONAL_SKIN_SIZE = {1024, 1024};
    // @UV-END REGIONAL_SKIN
}
