package xyz.przemyk.simpleplanes.client.render.models;

import java.util.Map;

import static java.util.Map.entry;

/**
 * Where each named cube's UV net starts in the airliner textures, one table per size and layer: the metal layer
 * ({@code *_metal.png}, 256x256, also the fans) and the painted skin ({@code *_skin.png}). Generated together
 * with the textures from the cube list of {@link AirlinerShape}; do not edit by hand.
 */
final class AirlinerUv {

    private AirlinerUv() {}

    // @UV-BEGIN WIDE_METAL
    static final Map<String, int[]> WIDE_METAL = Map.ofEntries(
            entry("belt", new int[]{0, 0}),
            entry("cockpit_side", new int[]{47, 16}),
            entry("ws_upper", new int[]{88, 9}),
            entry("ws_lower", new int[]{88, 15}),
            entry("dash", new int[]{88, 0}),
            entry("door", new int[]{240, 18}),
            entry("cowl", new int[]{0, 0}),
            entry("pylon", new int[]{202, 0}),
            entry("logo_0", new int[]{170, 0}),
            entry("logo_1", new int[]{88, 22}),
            entry("logo_2", new int[]{173, 59}),
            entry("logo_3", new int[]{0, 95}),
            entry("logo_4", new int[]{61, 95}),
            entry("logo_5", new int[]{122, 95}),
            entry("crew_base", new int[]{120, 22}),
            entry("crew_back", new int[]{88, 22}),
            entry("crew_head", new int[]{88, 39}),
            entry("seat_base", new int[]{0, 32}),
            entry("seat_back", new int[]{0, 45}),
            entry("seat_head", new int[]{141, 43}),
            entry("winglet_a", new int[]{227, 0}),
            entry("winglet_b", new int[]{149, 29}),
            entry("lip_h", new int[]{46, 0}),
            entry("lip_v", new int[]{0, 0}),
            entry("exhaust", new int[]{32, 42}),
            entry("plug", new int[]{70, 7}),
            entry("apu", new int[]{120, 37}),
            entry("nose_strut", new int[]{227, 0}),
            entry("main_strut", new int[]{66, 15}),
            entry("nose_tyre", new int[]{244, 0}),
            entry("main_tyre", new int[]{202, 0}),
            entry("spinner", new int[]{46, 10}),
            entry("blade", new int[]{46, 6}));
    // @UV-END WIDE_METAL

    // @UV-BEGIN WIDE_SKIN
    static final Map<String, int[]> WIDE_SKIN = Map.ofEntries(
            entry("body_lower", new int[]{243, 0}),
            entry("body_upper", new int[]{257, 137}),
            entry("hull_low", new int[]{622, 137}),
            entry("hull_high", new int[]{0, 144}),
            entry("fuselage_shoulder_top", new int[]{0, 0}),
            entry("fuselage_crown_low", new int[]{608, 0}),
            entry("fuselage_crown", new int[]{231, 268}),
            entry("fuselage_shoulder_bottom", new int[]{498, 266}),
            entry("fuselage_keel", new int[]{0, 272}),
            entry("fuselage_fairing", new int[]{484, 0}),
            entry("nose_1", new int[]{831, 40}),
            entry("nose_2", new int[]{0, 53}),
            entry("nose_3", new int[]{484, 56}),
            entry("nose_4", new int[]{908, 78}),
            entry("nose_5", new int[]{484, 81}),
            entry("nose_6", new int[]{960, 0}),
            entry("nose_7", new int[]{700, 22}),
            entry("tail_1", new int[]{831, 0}),
            entry("tail_2", new int[]{243, 46}),
            entry("tail_3", new int[]{831, 75}),
            entry("tail_4", new int[]{0, 0}),
            entry("fin_fillet", new int[]{0, 22}),
            entry("fin_1", new int[]{657, 40}),
            entry("fin_2", new int[]{78, 0}),
            entry("fin_3", new int[]{312, 0}),
            entry("fin_4", new int[]{243, 0}),
            entry("fin_5", new int[]{637, 0}),
            entry("fin_6", new int[]{78, 0}),
            entry("wing_1", new int[]{0, 0}),
            entry("wing_2", new int[]{243, 0}),
            entry("wing_3", new int[]{637, 0}),
            entry("wing_4", new int[]{926, 45}),
            entry("wing_5", new int[]{952, 17}),
            entry("wing_6", new int[]{243, 83}),
            entry("stab_1", new int[]{577, 61}),
            entry("stab_2", new int[]{484, 24}),
            entry("stab_3", new int[]{78, 34}),
            entry("stab_4", new int[]{507, 0}),
            entry("pillar_0", new int[]{78, 0}),
            entry("pillar_1", new int[]{93, 0}),
            entry("pillar_2", new int[]{700, 0}),
            entry("pillar_3", new int[]{110, 0}),
            entry("pillar_4", new int[]{243, 0}),
            entry("pillar_5", new int[]{266, 0}),
            entry("pillar_6", new int[]{312, 0}),
            entry("pillar_7", new int[]{340, 0}),
            entry("pillar_8", new int[]{484, 0}),
            entry("pillar_9", new int[]{656, 0}),
            entry("pillar_10", new int[]{700, 0}),
            entry("pillar_11", new int[]{484, 0}));
    static final int[] WIDE_SKIN_SIZE = {1024, 1024};
    // @UV-END WIDE_SKIN

    // @UV-BEGIN REGIONAL_METAL
    static final Map<String, int[]> REGIONAL_METAL = Map.ofEntries(
            entry("belt", new int[]{0, 0}),
            entry("cockpit_side", new int[]{222, 6}),
            entry("ws_upper", new int[]{100, 0}),
            entry("ws_lower", new int[]{171, 0}),
            entry("dash", new int[]{0, 0}),
            entry("door", new int[]{0, 9}),
            entry("cowl", new int[]{132, 6}),
            entry("pylon", new int[]{58, 0}),
            entry("logo_0", new int[]{100, 6}),
            entry("logo_1", new int[]{161, 7}),
            entry("logo_2", new int[]{0, 9}),
            entry("logo_3", new int[]{193, 37}),
            entry("logo_4", new int[]{168, 96}),
            entry("logo_5", new int[]{0, 107}),
            entry("crew_base", new int[]{193, 7}),
            entry("crew_back", new int[]{225, 32}),
            entry("crew_head", new int[]{61, 20}),
            entry("seat_base", new int[]{32, 20}),
            entry("seat_back", new int[]{61, 44}),
            entry("seat_head", new int[]{225, 49}),
            entry("winglet_a", new int[]{100, 6}),
            entry("winglet_b", new int[]{193, 22}),
            entry("lip_h", new int[]{32, 9}),
            entry("lip_v", new int[]{241, 0}),
            entry("exhaust", new int[]{64, 28}),
            entry("plug", new int[]{80, 0}),
            entry("apu", new int[]{100, 24}),
            entry("nose_strut", new int[]{100, 6}),
            entry("main_strut", new int[]{132, 6}),
            entry("nose_tyre", new int[]{80, 8}),
            entry("main_tyre", new int[]{171, 7}),
            entry("spinner", new int[]{222, 7}),
            entry("blade", new int[]{32, 15}));
    // @UV-END REGIONAL_METAL

    // @UV-BEGIN REGIONAL_SKIN
    static final Map<String, int[]> REGIONAL_SKIN = Map.ofEntries(
            entry("body_lower", new int[]{0, 145}),
            entry("body_upper", new int[]{0, 427}),
            entry("hull_low", new int[]{0, 562}),
            entry("hull_high", new int[]{0, 695}),
            entry("fuselage_shoulder_top", new int[]{0, 0}),
            entry("fuselage_crown_low", new int[]{0, 286}),
            entry("fuselage_crown", new int[]{203, 152}),
            entry("fuselage_shoulder_bottom", new int[]{0, 827}),
            entry("fuselage_keel", new int[]{195, 288}),
            entry("fuselage_fairing", new int[]{211, 0}),
            entry("nose_1", new int[]{0, 43}),
            entry("nose_2", new int[]{425, 38}),
            entry("nose_3", new int[]{0, 78}),
            entry("nose_4", new int[]{292, 78}),
            entry("nose_5", new int[]{211, 84}),
            entry("nose_6", new int[]{433, 89}),
            entry("nose_7", new int[]{416, 19}),
            entry("tail_1", new int[]{323, 0}),
            entry("tail_2", new int[]{211, 47}),
            entry("tail_3", new int[]{81, 70}),
            entry("tail_4", new int[]{211, 0}),
            entry("fin_fillet", new int[]{416, 0}),
            entry("fin_1", new int[]{384, 38}),
            entry("fin_2", new int[]{64, 0}),
            entry("fin_3", new int[]{89, 34}),
            entry("fin_4", new int[]{96, 0}),
            entry("fin_5", new int[]{0, 0}),
            entry("fin_6", new int[]{64, 0}),
            entry("wing_1", new int[]{0, 0}),
            entry("wing_2", new int[]{416, 0}),
            entry("wing_3", new int[]{292, 47}),
            entry("wing_4", new int[]{345, 40}),
            entry("wing_5", new int[]{349, 84}),
            entry("stab_1", new int[]{440, 69}),
            entry("stab_2", new int[]{388, 84}),
            entry("stab_3", new int[]{475, 19}),
            entry("stab_4", new int[]{64, 16}),
            entry("pillar_0", new int[]{64, 0}),
            entry("pillar_1", new int[]{79, 0}),
            entry("pillar_2", new int[]{0, 21}),
            entry("pillar_3", new int[]{0, 0}),
            entry("pillar_4", new int[]{19, 0}),
            entry("pillar_5", new int[]{406, 0}),
            entry("pillar_6", new int[]{96, 0}),
            entry("pillar_7", new int[]{475, 0}),
            entry("pillar_8", new int[]{119, 0}),
            entry("pillar_9", new int[]{17, 21}),
            entry("pillar_10", new int[]{435, 0}),
            entry("pillar_11", new int[]{211, 22}),
            entry("pillar_12", new int[]{493, 0}),
            entry("pillar_13", new int[]{475, 0}));
    static final int[] REGIONAL_SKIN_SIZE = {512, 1024};
    // @UV-END REGIONAL_SKIN
}
